### ISSUE TITLE
pip install issue

### ISSUE THREAD

**Issue by bekerov** [gunthercox/chatterbot-weather#3]
Hello. I have issue when `pip install chatterbot-weather` on windows 7
Can you please help with this?
![image](https://cloud.githubusercontent.com/assets/2405629/21041620/53576f88-bdfd-11e6-9002-ec25bf442df3.png)

**Comment by gunthercox** [comment]
Hi, I've corrected the issue by adding the `requirements.txt` file to the files listed in `MANIFIST.in`. This makes it so that `requirements.txt` gets included in the package that gets uploaded to PyPi. You should be able to install it successfully now.

Keep in mind that that this weather adapter is rather limited in what it can do and I haven't put much time into developing it further.
