### ISSUE TITLE
No Response

### ISSUE THREAD

**Issue by ayushecps** [gunthercox/chatterbot-weather#5]
I just used below:

 logic_adapters=[
        'chatterbot_weather.WeatherLogicAdapter'
    ]

**Comment by gunthercox** [comment]
Hi @ayushecps I believe that the weather forcasting API that the `chatterbot-weather` module connects to is no longer active, or that it has changed. I haven't had a chance to look into this to confirm it though.

Due to the large number of improvements being worked on for the main ChatterBot package, I don't necessarily have time to devote to making this fix right now. Maybe there is someone out there who would be willing to investigate and contribute a fix?

Also, apologies, but it seems that this issue was already reported (see #4 for details). I'm going to close this off and mark it as a duplicate. Feel free to follow and/or leave comments on ticket #4
